version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  groups:
    required-packages:
      dependency-type: production
      patterns:
        - "*"
    optional-packages:
      dependency-type: development
      patterns:
        - "highsbox"
        - "llvmlite"
