repeat: 1 # TODO repeat
timeout: 1200 # seconds, per run
name: "main"
problems:
  simple_problem:
    size: [10000, 100000, 1000000, 10000000, 50000000]
    inputs:
      - "input_10000.parquet"
      - "input_100000.parquet"
      - "input_1000000.parquet"
      - "input_10000000.parquet"
      - "input_50000000.parquet"
  facility_location:
    size: [16, 32, 64, 128, 192]
    construct_only: true
  # energy_planning:
  #   inputs: "*"
  #   size: [2, 4, 24, 168, 730, 8670]

solvers:
  - gurobi
  # - highs
  # - mosek

libraries:
  - pyoframe
  - pyomo
  - cvxpy
  - gurobipy
  - jump
  - linopy
  - pyoptinterface
  - pulp
  - ampl
