repeat: 1 # TODO repeat
timeout: 600 # seconds, per run
problems:
  # memory_overhead:
  #   repeat: 5
  simple_problem:
    size: [1000, 10000, 100000, 1000000, 10000000]
    inputs:
      - "input_1000.parquet"
      - "input_10000.parquet"
      - "input_100000.parquet"
      - "input_1000000.parquet"
      - "input_10000000.parquet"
  # create_variable:
  #   size: [10000, 100000, 1000000, 10000000, 100000000]
  # facility_location:
  #   size: [2, 4, 8, 16, 32, 64, 128, 256, 512]
  #   construct_only: true
  # energy_planning:
  #   inputs: "*"
  #   size: [2, 4, 24, 168, 730, 8670]
  # dummy_model:
  #   size: [2, 100, 200, 300, 400, 500, 1000, 2000]

solvers:
  - gurobi
  # - highs
  # - mosek

libraries:
  - pyoframe
  # - pyomo
  # - cvxpy
  # - gurobipy
  # - jump
  # - linopy
  # - pyoptinterface
  # - pulp
  # - ampl
